#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
   export API_KEY=45867622
   export API_SECRET=f2a6b3f0627d0b1c7603194781765623754431e3
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S https://first-proj-1.herokuapp.com/ -t web web/index.php
