#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
   export API_KEY=45785862
   export API_SECRET=39f2736f837834a4ff1e33a3f1d90cd94670d610
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S 0.0.0.0:8080 -t web web/index.php
